spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/festify
    username: user
    password: secret
    # driver-class-name: org.postgresql.Driver   # opcional, se infiere por la URL
  jpa:
    hibernate:
      ddl-auto: validate # o validate/create/create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
springdoc:
  api-docs:
    path=/api-docs: